edxl_cap_v1_2/Controllers/EdxlCapMsgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using edxl_cap_v1_2.Data;
using edxl_cap_v1_2.Models;
using edxl_cap_v1_2.Models.ContentViewModels;

namespace edxl_cap_v1_2.Controllers
{
    public class EdxlCapMsgController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EdxlCapMsgController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EdxlCapMessages
        public async Task<IActionResult> Index()
        {
            List<EdxlCapMsg> identifierlist = new List<EdxlCapMsg>();

            //------Getting Data fom Database using EntityFrameworkCore------
            identifierlist = (from product in _context.EdxlCapMsg
                              select product).ToList();

            //------Inserting Select Item in List------
            identifierlist.Insert(0, new EdxlCapMsg { Id = 0, Alert_Identifier = "Select" });

            //------Assigning identifierlist to ViewBag.ListofIdentifier------
            ViewBag.ListofIdentifier = identifierlist;


            return View(await _context.EdxlCapMsg.ToListAsync());
        }

        [HttpPost]

        public IActionResult Index(EdxlCapMsg EdxlCapMsg)
        {
            //------Validation------
            if (EdxlCapMsg.Id == 0)
            {
                ModelState.AddModelError("", "Select EdxlCapMsg");
            }

            //------Getting selected value------
            int SelectedValue = EdxlCapMsg.Id;

            ViewBag.SelectedValue = EdxlCapMsg.Id;

            //------Setting Data back to ViewBag after Posting form------
            List<EdxlCapMsg> identifierlist = new List<Models.EdxlCapMsg>();

            identifierlist = (from product in _context.EdxlCapMsg
                           select product).ToList();

            identifierlist.Insert(0, new EdxlCapMsg { Id = 0, Alert_Identifier = "Select" });
            ViewBag.ListofIdentifier = identifierlist;

            return View();
        }

    }

    //// GET: EdxlCapMessages/Details/5
    //public async Task<IActionResult> Details(string id)
    //    {
    //        if (id == null)
    //        {
    //            return NotFound();
    //        }

    //        var edxlCapMsg = await _context.EdxlCapMsg
    //            .SingleOrDefaultAsync(m => m.Alert_Identifier == id);
    //        if (edxlCapMsg == null)
    //        {
    //            return NotFound();
    //        }

    //        return View(edxlCapMsg);
    //    }

    //    // GET: EdxlCapMessages/Create
    //    public IActionResult Create()
    //    {
    //        return View();
    //    }

    //    // POST: EdxlCapMessageViewModels/Create
    //    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    //    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    //    [HttpPost]
    //    [ValidateAntiForgeryToken]
    //    public async Task<IActionResult> Create([Bind("Alert_Identifier")] EdxlCapMsg edxlCapMsg)
    //    {
    //        if (ModelState.IsValid)
    //        {
    //            _context.Add(edxlCapMsg);
    //            await _context.SaveChangesAsync();
    //            return RedirectToAction(nameof(Index));
    //        }
    //        return View(edxlCapMsg);
    //    }

    //    // GET: EdxlCapMessages/Edit/5
    //    public async Task<IActionResult> Edit(string id)
    //    {
    //        if (id == null)
    //        {
    //            return NotFound();
    //        }

    //        var edxlCapMsg = await _context.EdxlCapMsg.SingleOrDefaultAsync(m => m.Alert_Identifier == id);
    //        if (edxlCapMsg == null)
    //        {
    //            return NotFound();
    //        }
    //        return View(edxlCapMsg);
    //    }

    //    // POST: EdxlCapMessages/Edit/5
    //    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    //    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    //    [HttpPost]
    //    [ValidateAntiForgeryToken]
    //    public async Task<IActionResult> Edit(string id, [Bind("Alert_Identifier")] EdxlCapMsg edxlCapMsg)
    //    {
    //        if (id != edxlCapMsg.Alert_Identifier)
    //        {
    //            return NotFound();
    //        }

    //        if (ModelState.IsValid)
    //        {
    //            try
    //            {
    //                _context.Update(edxlCapMsg);
    //                await _context.SaveChangesAsync();
    //            }
    //            catch (DbUpdateConcurrencyException)
    //            {
    //                if (!EdxlCapMsgExists(edxlCapMsg.Alert_Identifier))
    //                {
    //                    return NotFound();
    //                }
    //                else
    //                {
    //                    throw;
    //                }
    //            }
    //            return RedirectToAction(nameof(Index));
    //        }
    //        return View(edxlCapMsg);
    //    }

    //    // GET: EdxlCapMessages/Delete/5
    //    public async Task<IActionResult> Delete(string id)
    //    {
    //        if (id == null)
    //        {
    //            return NotFound();
    //        }

    //        var edxlCapMsg = await _context.EdxlCapMsg
    //            .SingleOrDefaultAsync(m => m.Alert_Identifier == id);
    //        if (edxlCapMsg == null)
    //        {
    //            return NotFound();
    //        }

    //        return View(edxlCapMsg);
    //    }

    //    // POST: EdxlCapMessages/Delete/5
    //    [HttpPost, ActionName("Delete")]
    //    [ValidateAntiForgeryToken]
    //    public async Task<IActionResult> DeleteConfirmed(string id)
    //    {
    //        var edxlCapMsg = await _context.EdxlCapMsg.SingleOrDefaultAsync(m => m.Alert_Identifier == id);
    //        _context.EdxlCapMsg.Remove(edxlCapMsg);
    //        await _context.SaveChangesAsync();
    //        return RedirectToAction(nameof(Index));
    //    }

    //    private bool EdxlCapMsgExists(string id)
    //    {
    //        return _context.EdxlCapMsg.Any(e => e.Alert_Identifier == id);
    //    }
    //}
}

edxl_cap_v1_2/Views/Shared/_CapCategoryLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/capv1_2_refimp.css" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <!-- Header -->
    <header>
        <div class="content-wrapper">
            @Html.Partial("_EdxlHeader")
        </div>
    </header>
    <!-- End of Header -->

    <!-- edxlLeftColumn -->
    <div id="edxlLeftColumn">
        @Html.Partial("_CapLeftColumnPartial")
    </div>
    <!-- End of edxlLeftColumn -->

    <!-- indexRightColumn-Content Body -->
    <div id="indexRightColumn" style="position:relative">
        @RenderBody()
        @RenderSection("scripts", required: false)
    </div>
    <!-- End of edxlRightColumn-Content Body -->  

    <!-- Footer -->
    <footer>
        <div class="content-wrapper" >
            @Html.Partial("_EdxlFooter")
        </div>
    </footer>

</body>
</html>

edxl_cap_v1_2/Views/Shared/_CapIntroLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/capv1_2_refimp.css" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <!-- Header -->
    <header>
        <div class="content-wrapper">
            @Html.Partial("_EdxlHeader")
        </div>
    </header>
    <!-- End of Header -->

    <!-- indexLeftColumn -->
    <div id="indexLeftColumn">
        @RenderSection("CapIntro")
    </div>
    <!-- End of indexLeftColumn -->

    <!-- indexRightColumn-Content Body -->
    <div id="indexRightColumn">
        @RenderBody()
    </div>
    <!-- End of indexRightColumn-Content Body -->

    <!-- Footer -->
    <footer>
        <div class="content-wrapper">
            @Html.Partial("_EdxlFooter")
        </div>
    </footer>

</body>
</html>

edxl_cap_v1_2/Views/Shared/_CapLeftColumnPartial.cshtml
@*
    For more information on enabling MVC for empty projects, 
    visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="css/capv1_2_refimp.css">
    <title>@ViewBag.Title="EDXL-CAP-v1.2 Reference Implementation"</title>
</head>

<body>
    <!-- edxlLeftColumn -->

    <div id="edxlLeftColumn">
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <h3>EDXL-CAP Data Categories</h3>
        <p></p>
        <p></p>

        <div class="edxlLeftColumn">
            <ul class="edxlLeftColumn ul" style="list-style-type: none">
                <li class="edxlLeftColumn ul li"><a asp-action="AlertSelect" asp-controller="alerts">Alert</a></li>
                <li class="edxlLeftColumn ul li"><a asp-action="InfoSelect" asp-controller="infos">Info</a></li>
                <li class="edxlLeftColumn ul li"><a asp-action="AreaSelect" asp-controller="areas">Area</a></li>
                <li class="edxlLeftColumn ul li"><a asp-action="ResourceSelect" asp-controller="resources">Resource</a></li>
            </ul>
        </div>
    </div>
</body>

<!-- End of edxlLeftColumn -->

edxl_cap_v1_2/Views/Shared/_EdxlCapSelect.cshtml
@model edxl_cap_v1_2.Models.EdxlCapMsg
@using edxl_cap_v1_2.Models

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="css/edxl_capv1_2_refimp.css">
    <title>@ViewBag.Title="EDXL-CAP-v1.2 Reference Implementation"</title>
</head>
<body>
    @{
        <form asp-controller="EdxlCapMsg" asp-action="Index" method="post" class="form-horizontal" role="form">
            <div class="form-group">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <div class="content-wrapper">
                    <span class="smallText">
                        <label asp-for="Alert_Identifier" class="control-label"></label>
                        <select asp-for="Id"
                                class="form-control"
                                asp-items="@(new SelectList(@ViewBag.ListofIdentifier,"Id", "Identifier"))"></select>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class="content-wrapper">
                    <input id="Submit1" type="submit" value="submit" />
                </div>
            </div>
            <div class="form-group">
                <div class="content-wrapper">
                    @if (ViewBag.SelectedValue != null)
                    {
                        <text>Selected Alert_Identifier: </text> @ViewBag.SelectedValue;
                    }
                </div>
            </div>
        </form>
    }

</body>

edxl_cap_v1_2/Views/Shared/_EdxlHeader.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="css/edxl_capv1_2_refimp.css">
    <title>@ViewBag.Title="EDXL-CAP-v1.2 Reference Implementation"</title>
</head>
<body>
    <div id="main">
            <div id="header">
                <div id="widgetBar">
                    <div class="headerWidget" style="float: right">
                        [ approve message pkg ]
                    </div>
                    <div class="headerWidget" style="float: right">
                        [ assemble message pkg ]
                    </div>
                    <div class="headerWidget" style="float: right">
                        [ review message ]
                    </div>
                    <div class="headerWidgetLeft" style="float: right">
                        @await  Html.PartialAsync("_LoginPartial")
                    </div>
                </div>

                <a href="#">
                    <img src="~/images/edxl-logo-01.jpg" id="logo" alt="EDXL logo">
                    <img src="~/images/edxlw.jpg" align="center" id="logoText" alt="EMERGENCY DATA EXCHANGE LANGUAGE">
                </a>

            </div>
            
        </div>

</body>

edxl_cap_v1_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/capv1_2_refimp.css" />
    <title>@ViewData["Title"] edxl_cap_v1_2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/custom.css" />
        <link rel="stylesheet" href="~/css/edxl_capv1_2_refimp.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/edxl_capv1_2_refimp.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <!-- Header -->
    <header>
        <div class="content-wrapper">
            @Html.Partial("_EdxlHeader")
        </div>
    </header>
    <!-- End of Header -->

    <!-- RenderBody -->
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <!-- End of RenderBody -->

    <!-- Footer -->
    <footer>
        <div class="content-wrapper">
            @Html.Partial("_EdxlFooter")
        </div>
    </footer>
    <!-- End of Footer -->

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>